site_name: Example Documenation Site
repo_url: https://github.com/Mokrecho1/MkDocs_Test
copyright: Proprietary information, for the express use of TIGA, A Tetra Tech Company
theme:
   name: material
   palette:
      scheme: slate
      primary: indigo
