site_name: [Client] Example Documenation Site
site_description: This is a test deployment of MKdocs via RTD Hosting.
repo_url: https://github.com/Mokrecho1/MkDocs_Test
copyright: TIGA 2024. Proprietary information, for the express use of TIGA, A Tetra Tech Company.
theme:
   name: material
   palette:
      scheme: slate
      primary: indigo
