site_name: MKDocs Test
site_description: This is a test deployment of MKdocs via RTD Hosting.
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  prev_next_buttons_location: none
